# charizard/utils/splitting_utils/splitter.py
"""
MS Splitting utilities.

run_split() does everything:
- Calculate SPW/channel ranges
- Create directories
- Write CASA scripts
- Submit jobs via housekeeper
- Wait for completion
- Verify outputs
- Return results
"""

import os
import time
from typing import Dict, List, Optional, Tuple

from housekeeper import Housekeeper

from ..general.tracker import JobTracker


def calculate_spw_ranges(channels_per_spw: int, 
                         total_spws: int, 
                         target_spws: int,
                         edge_percent: float = 5.0) -> Dict[str, str]:
    """
    Calculate channel ranges for splitting.
    
    Trims edge channels (5% by default) and distributes remaining channels
    across target SPWs.
    
    Original charizard logic from formalities.py.
    
    Args:
        channels_per_spw: Number of channels per SPW in input MS
        total_spws: Number of SPWs in input MS
        target_spws: Number of output SPWs to create
        edge_percent: Percentage of edge channels to trim (default 5%)
    
    Returns:
        Dict mapping spw name to channel selection string
        e.g., {'spw0': '0:205~1844', 'spw1': '0:1845~3484', ...}
    """
    
    # Calculate edge trimming
    edge_channels = int(channels_per_spw * edge_percent / 100)
    usable_start = edge_channels
    usable_end = channels_per_spw - edge_channels - 1
    usable_channels = usable_end - usable_start + 1
    
    # Total usable channels across all input SPWs
    total_usable = usable_channels * total_spws
    
    # Channels per output SPW
    channels_per_target = total_usable // target_spws
    
    spw_ranges = {}
    
    # Track position across all channels
    global_start = 0
    
    for target_idx in range(target_spws):
        # Calculate global channel range for this target SPW
        target_start = target_idx * channels_per_target
        target_end = target_start + channels_per_target - 1
        
        if target_idx == target_spws - 1:
            # Last SPW gets remaining channels
            target_end = total_usable - 1
        
        # Convert to per-input-SPW ranges
        ranges = []
        
        for input_spw in range(total_spws):
            # Global channel range for this input SPW
            spw_global_start = input_spw * usable_channels
            spw_global_end = spw_global_start + usable_channels - 1
            
            # Check overlap with target range
            overlap_start = max(target_start, spw_global_start)
            overlap_end = min(target_end, spw_global_end)
            
            if overlap_start <= overlap_end:
                # Convert back to local channel numbers
                local_start = (overlap_start - spw_global_start) + usable_start
                local_end = (overlap_end - spw_global_start) + usable_start
                
                ranges.append(f"{input_spw}:{local_start}~{local_end}")
        
        spw_name = f"spw{target_idx}"
        spw_ranges[spw_name] = ';'.join(ranges)
    
    return spw_ranges


def build_split_script(ms_path: str,
                       spw_range: str,
                       output_dir: str,
                       calibrators: List[str],
                       targets: List[str],
                       correlation: str = '') -> str:
    """
    Build CASA script for splitting MS.
    
    Args:
        ms_path: Path to input MS
        spw_range: SPW selection string (e.g., "0:205~1844")
        output_dir: Output directory (e.g., "spw0")
        calibrators: List of calibrator field names
        targets: List of target field names
        correlation: Correlation selection (e.g., 'RR,LL' or '' for all)
    
    Returns:
        CASA Python script as string
    """
    
    cal_string = ','.join(calibrators) if calibrators else ''
    target_string = ','.join(targets) if targets else ''
    corr_param = f",\n    correlation='{correlation}'" if correlation else ''
    
    script = f'''# CASA split script for {output_dir}
# Auto-generated by Charizard

import os

# Ensure output directory exists
os.makedirs('{output_dir}', exist_ok=True)
os.makedirs('{output_dir}/caltables', exist_ok=True)
os.makedirs('{output_dir}/plots', exist_ok=True)

'''
    
    # Split calibrators
    if calibrators:
        script += f'''
# Split calibrators
print("Splitting calibrators to {output_dir}/cal.ms")
mstransform(
    vis='{ms_path}',
    outputvis='{output_dir}/cal.ms',
    field='{cal_string}',
    spw='{spw_range}',
    datacolumn='data',
    regridms=False,
    chanaverage=False,
    keepflags=True{corr_param}
)
print("Calibrator split complete")
'''
    
    # Split targets
    if targets:
        script += f'''
# Split targets
print("Splitting targets to {output_dir}/src.ms")
mstransform(
    vis='{ms_path}',
    outputvis='{output_dir}/src.ms',
    field='{target_string}',
    spw='{spw_range}',
    datacolumn='data',
    regridms=False,
    chanaverage=False,
    keepflags=True{corr_param}
)
print("Target split complete")
'''
    
    script += '''
print("Split complete!")
'''
    
    return script


def run_split(hk: Housekeeper,
              config,
              ms_info: Dict,
              cal_plan: Dict,
              tracker: JobTracker,
              logger,
              whitelist: List[str]) -> bool:
    """
    Run the split step.
    
    Does everything:
    - Determine correlation selection based on polcal
    - Calculate SPW ranges
    - Create directories
    - Write CASA scripts
    - Submit jobs
    - Wait for completion
    - Verify outputs
    - Update tracker
    
    Args:
        hk: Housekeeper instance
        config: PipelineConfig
        ms_info: MS info dict
        cal_plan: Calibration plan dict
        tracker: JobTracker instance
        logger: Logger
        whitelist: Error whitelist for log checking
    
    Returns:
        True if successful (at least one SPW succeeded)
    """
    
    # =========================================================================
    # DETERMINE CORRELATION SELECTION
    # =========================================================================
    # Check if polcal is possible
    do_polcal = (cal_plan.get('leakage_cal') and 
                 cal_plan.get('polangle_cal') and 
                 cal_plan.get('polangle_cal') in cal_plan.get('polcal_models', {}))
    
    # Get MS correlations
    corr_names = ms_info.get('corr_names', [])
    pol_basis = ms_info.get('pol_basis', 'unknown')
    num_corrs = ms_info.get('num_corrs', 4)
    
    logger.info(f"MS correlations: {corr_names} ({pol_basis} basis)")
    
    # Determine correlation selection
    correlation = ''  # Empty = all correlations
    
    if num_corrs == 4:
        if do_polcal:
            logger.info("Full polarization calibration enabled - keeping all correlations")
            correlation = ''
        else:
            # No polcal - use only parallel hands to save memory
            if pol_basis == 'circular':
                correlation = 'RR,LL'
                logger.info("No polcal - splitting only parallel hands (RR,LL)")
            elif pol_basis == 'linear':
                correlation = 'XX,YY'
                logger.info("No polcal - splitting only parallel hands (XX,YY)")
            else:
                logger.warning("Unknown polarization basis - keeping all correlations")
                correlation = ''
    else:
        logger.info(f"MS has {num_corrs} correlations - keeping all")
    
    # =========================================================================
    # CALCULATE SPW RANGES
    # =========================================================================
    spw_ranges = calculate_spw_ranges(
        channels_per_spw=ms_info['num_channels'],
        total_spws=ms_info['num_spws'],
        target_spws=config.target_spws
    )
    
    logger.info(f"Splitting into {len(spw_ranges)} SPWs")
    for spw, rng in spw_ranges.items():
        logger.info(f"  {spw}: {rng}")
    
    # Create directories
    for spw in spw_ranges:
        os.makedirs(f"{spw}/caltables", exist_ok=True)
        os.makedirs(f"{spw}/plots", exist_ok=True)
    
    # Get environment
    casa_path = config.environment.get('casa_path', '')
    preamble = config.environment.get('shell_preamble', '')
    resources = config.resources.get('default', {})
    
    # Submit jobs
    logger.substep("Submitting split jobs...")
    job_map = {}  # job_id -> spw
    
    for spw, chan_range in spw_ranges.items():
        # Build script
        script = build_split_script(
            ms_path=config.ms_path,
            spw_range=chan_range,
            output_dir=spw,
            calibrators=cal_plan['all_calibrators'],
            targets=cal_plan['targets'],
            correlation=correlation
        )
        
        # Write script file
        script_file = f"split_{spw}.py"
        with open(script_file, 'w') as f:
            f.write(script)
        
        # Build command
        command = f"""cd {os.getcwd()}
{preamble}
{casa_path}/bin/casa --nologger --nogui -c {script_file}
"""
        
        # Submit
        job = hk.submit(
            command=command,
            name=f"split_{spw}",
            job_subdir=spw,
            ppn=resources.get('ppn', 4),
            walltime=resources.get('walltime', '04:00:00')
        )
        
        if job.job_id:
            job_map[job.job_id] = spw
            logger.info(f"  Submitted {spw}: job {job.job_id}")
        else:
            logger.error(f"  Failed to submit {spw}")
            tracker.mark_failed(spw, 'split', 'Job submission failed')
        
        time.sleep(0.5)  # Small delay between submissions
    
    if not job_map:
        logger.error("No jobs submitted!")
        return False
    
    # Wait for jobs
    logger.substep(f"Waiting for {len(job_map)} split jobs...")
    results = hk.wait_and_check(list(job_map.keys()), whitelist=whitelist)
    
    # Process results
    successful = []
    failed = []
    
    for job_id, (job, log_result) in results.items():
        spw = job_map.get(job_id, 'unknown')
        
        # Check log result
        if not log_result.success:
            failed.append(spw)
            tracker.mark_failed(spw, 'split', f"Log errors: {log_result.error_lines[:1]}")
            logger.error(f"  {spw}: FAILED (log errors)")
            for err in log_result.error_lines[:3]:
                logger.error(f"    {err}")
            continue
        
        # Verify outputs exist
        cal_exists = os.path.exists(f"{spw}/cal.ms")
        src_exists = os.path.exists(f"{spw}/src.ms") or not cal_plan['targets']
        
        if cal_exists and src_exists:
            successful.append(spw)
            tracker.mark_success(spw, 'split')
            logger.info(f"  {spw}: OK")
        else:
            failed.append(spw)
            missing = []
            if not cal_exists:
                missing.append("cal.ms")
            if not src_exists:
                missing.append("src.ms")
            tracker.mark_failed(spw, 'split', f"Missing outputs: {missing}")
            logger.error(f"  {spw}: FAILED (missing {missing})")
    
    # Summary
    logger.info(f"Split results: {len(successful)} succeeded, {len(failed)} failed")
    
    return len(successful) > 0
